- name: Install dependencies
  become: true
  apt:
    name:
      - python3-psutil
    state: present

- name: Set keybindings variable
  set_fact:
    keybindings:
      - name: move-to-workspace-down
        value: "['<Primary><Alt>Down']"
      - name: move-to-workspace-up
        value: "['<Primary><Alt>Up']"
      - name: switch-to-workspace-down
        value: "['<Primary>Down']"
      - name: switch-to-workspace-up
        value: "['<Primary>Up']"
      - name: move-to-workspace-left
        value: "['<Primary><Alt>Left']"
      - name: move-to-workspace-right
        value: "['<Primary><Alt>Right']"
      - name: switch-to-workspace-left
        value: "['<Primary>Left']"
      - name: switch-to-workspace-right
        value: "['<Primary>Right']"

- name: Keybindings
  dconf:
    key: /org/gnome/desktop/wm/keybindings/{{ item.name }}
    value: "{{ item.value }}"
  loop: "{{ keybindings }}"

- name: Change caps behavior
  dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps']"
