- name: Install gnome tools
  become: true
  apt:
    name:
      - gnome-tweak-tool
      - fcitx5-mozc
      - language-pack-gnome-ja
      - fonts-noto-cjk-extra
      - gnome-getting-started-docs-ja
      - gnome-user-docs-ja
    state: present

- name: Setup keybindings
  include: keybind.yml

- name: Setup favorite apps
  include: favorite_apps.yml

- name: Setup display scaling
  include: scaling.yml

- name: Setup mice
  include: mouse.yml

- name: Setup theme
  include: theme.yml

- name: Install X11 packages
  include: x11.yml

- name: Install GTK packages
  include: gtk.yml

