- name: Install X11 packages
  become: true
  apt:
    name:
      - libx11-dev
      - libxcursor-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxi-dev
      - libxxf86vm-dev
      - mesa-common-dev
    state: present

