- name: Install dev tools
  become: true
  apt:
    name:
      - cmake
      - libssl-dev
      - build-essential
      - ccache
      - openjdk-8-jdk
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - libncurses5
      - libboost-dev
    state: present

- name: Install dev tools (snap, classic)
  become: true
  snap:
    name:
      - flutter
      - intellij-idea-community
      - android-studio
      - node
    classic: yes

- name: Install git
  include: git.yml

- name: Setup docker
  include: docker.yml

- name: Install X11 packages
  include: x11.yml

- name: Install GTK packages
  include: gtk.yml

- name: Install AtCoder tools
  include: atcoder.yml

