- name: Install dev tools
  become: true
  apt:
    name:
      - python3-pip
      - cmake
      - libssl-dev
      - build-essential
      - ccache
      - openjdk-8-jdk
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - libncurses5
      - libboost-dev
      - libhidapi-dev
    state: present

- name: Install dev tools (snap, classic)
  become: true
  snap:
    name:
      - flutter
      - node
    classic: yes

- name: Install git
  include: git.yml

- name: Setup docker
  include: docker.yml

- name: Install AtCoder tools
  include: atcoder.yml

- name: Install Google Cloud Platform tools
  include: gcp.yml

