- name: Install pip3
  become: true
  apt:
    name:
      - python3-pip
    state: present

- name: Install mlagents
  pip:
    name: mlagents
    executable: pip3

- name: Install pwn
  pip:
    name: pwn
    executable: pip3
