- name: Check rust
  stat:
    path: "{{ home }}/.cargo/bin/rustup"
  register: rust

- name: Create temporary directory
  when: not rust.stat.exists
  tempfile:
    state: directory
    suffix: rust
  register: rust_tmp

- name: Download script
  when: not rust.stat.exists
  get_url:
    dest: "{{ rust_tmp.path }}/init.sh"
    url: https://sh.rustup.rs/

- name: Run script
  when: not rust.stat.exists
  command: "sh {{ rust_tmp.path }}/init.sh -y"

- name: Cleanup temporary directory
  when: not rust.stat.exists
  file:
    path: "{{ rust_tmp }}"
    state: absent

- name: Check cargo-make
  stat:
    path: "{{ home }}/.cargo/bin/cargo-make"
  register: cargo_make

- name: Install cargo-make
  when: not cargo_make.stat.exists
  command: "OPENSSL_INCLUDE_DIR=/usr/include/openssl/ OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu/ {{ home }}/.cargo/bin/cargo install cargo-make"

- name: Check cargo-expand
  stat:
    path: "{{ home }}/.cargo/bin/cargo-expand"
  register: cargo_expand

- name: Install cargo-expand
  when: not cargo_expand.stat.exists
  command: "{{ home }}/.cargo/bin/cargo install cargo-expand"

