- name: Install common tools
  become: true
  apt:
    name:
      - vim
      - tmux
      - curl
      - fcitx5-mozc
      - language-pack-gnome-ja
      - fonts-noto-cjk-extra
      - gnome-getting-started-docs-ja
      - gnome-user-docs-ja
    state: present

- name: Configure tmux
  become: true
  copy:
    src: "{{ playbook_dir }}/files/tmux.conf"
    dest: "/etc/tmux.conf"

