- name: Install common tools
  become: true
  apt:
    name:
      - vim
      - tmux
      - curl
      - tlp
      - acpi-call-dkms
    state: present

- name: Configure tmux
  become: true
  copy:
    src: "{{ playbook_dir }}/files/tmux.conf"
    dest: "/etc/tmux.conf"

